apiVersion: v1
kind: Service
metadata:
  name: es8-service
  namespace: myprojects
spec:
  selector:
    app: es8
  ports:
  - name: "port0"
    port: 9300
    protocol: TCP
    targetPort: 9300
    nodePort: 30093
  - name: "port1"
    port: 9200
    protocol: TCP
    targetPort: 9200
    nodePort: 30092
  type: NodePort
