apiVersion: apps/v1
kind: Deployment
metadata:
  name: es8
  namespace: myprojects
spec:
  selector:
    matchLabels:
      app: es8
  template:
    metadata:
      labels:
        app: es8
    spec:
      containers:
      - name: es8
        image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
        resources:
          limits:
            memory: "2048Mi"
            cpu: "2048m"
        ports:
          - containerPort: 9200
          - containerPort: 9300

        # 使用的数据卷
        volumeMounts:
          - mountPath: "/vol"
            name: myvol
        

      - name: kibana
        image: docker.elastic.co/kibana/kibana:8.1.2
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
          - containerPort: 5601

      # 数据卷
      volumes:
        - name: myvol
          persistentVolumeClaim:
            claimName: mypvc




