apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: myprojects
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
